name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: echo Build
      - name: Unit tests
        run: echo Build
      - name: Integration tests
        run: Integration tests

  deploy-on-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Deploy on INTEG environment
        run: echo Deploy on INTEG environment

  deploy-on-uat:
    needs: [build, deploy-on-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Deploy on UAT environment
        run: echo Deploy on UAT environment
